### ISSUE TITLE
`bp_bulk_load_gff` fails to compile

### ISSUE THREAD

**Issue by cjfields** [bioperl/Bio-DB-GFF#1]
_From @carandraug on September 17, 2018 14:19_

```
"my" variable $AUTH masks earlier declaration in same scope at bin/bp_bulk_load_gff line 656.
"my" variable $db masks earlier declaration in same scope at bin/bp_bulk_load_gff line 666.
at t/00-compile.t line 812, <GEN2696> line 3.
```

_Copied from original issue: bioperl/bioperl-live#286_

**Comment by cjfields** [comment]
Interesting; glad to see `dzil` is catching these.  This used to be used for loading older sequence features IIRC and has largely been superseded by `Bio:DB::SeqFeature`. I wonder if this simply hasn't been tested with newer perl releases

**Comment by cjfields** [comment]
_From @carandraug on October 7, 2018 22:9_

I have moved this program to the distribution https://github.com/bioperl/Bio-DB-GFF so this is no longer a issue here. Can someone move the issue to there, please?

**Comment by carandraug** [comment]
For what is worth, this issue was introduced in bioperl/bioperl-live@51c93744fff1e665ab96d04a387bf1c

This bug seems to have been introduced since version 1.6.9 (tag `bioperl-release-1-6-9`). This was so long ago, and no one has reported the issue before so maybe just remove it.

**Comment by cmdcolin** [comment]
I went ahead and made it compile by simply redeclaring some variables. I would be very happy to review the change I made but I'd like to push this forward with a CPAN release :)

**Comment by cjfields** [comment]
Seems to be addressed and is passing tests, closing this ticket.
